name: PancakeCore
version: '${version}'
main: dev.vansen.pancakecore.PancakeCore
api-version: '1.21'
loader: dev.vansen.pancakecore.loader.PancakeLoader
dependencies:
  server:
    Vault:
      load: AFTER
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: AFTER
      required: false
      join-classpath: true